### ISSUE TITLE
After Payment no redirect

### ISSUE THREAD

**Issue by computerworxdev** [paylike/plugin-opencart-2.3#4]
Hi 
I Just installed that plug in on Open Cart 2.3.0.2
I use default template. Plugin was installed and activated.
From Paylike account I entered 
- TESTMODE PUBLIC KEY
- TESTMODE APP KEY
and 
- TRANSACTION MODE: TEST
- STATUS: ENABLED
- ORDER STATUS: COMPLETE
- CAPTURE: INSTANT

what happens is that when I enter test card I get a green Check Sign in window when processing payment

Then PAY BUTTON changes to Confirm Order and when clicked again I get the same Credit card Window to enter number again.

after that it does the same thing
Its in the loop and can not continue.

In Backend DASHBOARD order does not show processed and looks like nothing is happening.

I thought after the test Payment I should get Confirmation Page + an order placed in BACKEND ADMIN with status COMPLETE but nothing happened.

It gets Stuck in Checkout Cart on credit Card Entry.
Can you please have a look what is wrong with it ?

Thanks

**Comment by ionutcalara** [comment]
Hi there, can you email the site url where you encouter this issue at ionut@derikon.com ?

**Comment by computerworxdev** [comment]
Hello
well for security reasons i can not provide live site url.
Also due to the fact i was not getting response in timely matter i had to hire another coder to look into the extension.
Currently the extension was fixed and it was due to API with paylike..  your extension needs to be fixed for newer versions of OC.
The best way for you is to install OC version 2.3.0.2 and that plug in then you can use the test account from paylike to perform testing and you will see that it does not process on Open Cart side... it does send it to paylike and records transactions but do not get processed in OpenCart.
I can ask him to comment on this issue later here to explain his fix if he is willing.
But in current state its not functional.

**Comment by ionutcalara** [comment]
Hi, 
I am sorry about the delay, we already have succesfully tested this here: http://opencart23.derikon.com. Its the default installation and it works both on the frontend and on the backend side. If you can't provide the url, maybe you can provide details about the installation so we can try to replicate the issue.

**Comment by computerworxdev** [comment]
i will contact the coder to comment on the issue here...

Thanks

**Comment by ionutcalara** [comment]
We could move to email if that would be better so that we can also share more details to get to the bottom of this.

**Comment by femotizo** [comment]
Hi @ionutcalara 
Using a fresh installation of Open Cart 2.3.0.2.
Paylike plugin file as recieved was installed.

**1, Create a transaction** : _fine!_
**2, Capture a transaction**:
When **Paylike > process_payment()** (Capture Transaction) is called, it doesn't send the **public_key** along with the order data and it returns Status code **401** Unauthorized.

i noticed that **Adapter > request()** was sending only the **ApiKey** data

`            curl_setopt( $ch, CURLOPT_USERPWD, ":" . $this->apiKey );`

the _Basic Authorization_ requires both fields and it seems the public key wasnt present, i passed it and the transaction was captured
`            curl_setopt( $ch, CURLOPT_USERPWD, $this->appKey.':'.$this->apiKey );`

Thanks

**Comment by ionutcalara** [comment]
Hi @femotizo, please see the documentation regarding authentification here: https://github.com/paylike/api-docs#authenticating
 
It does not need both keys, the same adapter is being used on all plugins (WooCommerce,Magento, Easy digital downloads, Prestashop, Opencart) and capturing is working, it seems unlikely that this was the issue that @computerworxdev was talking about as he said something about getting the credit card window multiple times. 
Can you try reverting the changes in the adapter and test it like that?

**Comment by ionutcalara** [comment]
I am closing this for now, but feel free to reopen
